### PR TITLE
Fix margin isssue

### PR DESCRIPTION
**Pull request by johnthepink**
Fix for this:

screenshot 2015-08-03 14 43 57

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@johnthepink when does this occur?

**Comment by johnthepink** [comment]
@jbaxleyiii I was seeing it on pretty much every page. I tried to track down a commit that would have caused it and didn't see anything right away.

**Comment by jbaxleyiii** [comment]
@johnthepink I've seen a super rare instance where sass will recompile and .hard will be mapped to .soft-sides, I wonder if that happened? Its not doing this on alpha.newspring.io right now

**Comment by johnthepink** [comment]
@jbaxleyiii it was a margin-left and margin-right on the `lap-and-up-seven-twelfths` class that was causing it

**Comment by jbaxleyiii** [comment]
@johnthepink super weird

**Comment by johnthepink** [comment]
@jbaxleyiii it's actually not doing it for me now without the fix. did junction get rebuilt? or maybe i was between builds or something?

**Comment by jbaxleyiii** [comment]
@johnthepink it may have been between builds. Or magic

**Pull request merged**
