### PR TITLE
Feature loading

### PR DESCRIPTION
**Pull request by johnthepink**
@samclaridge is good with this.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
loading

@johnthepink 
Can we potentially use a `{{Template.contentBlock}}` for this [section](https://github.com/NewSpring/apollos-give/blob/feature-loading/_source/client/objects/profile/loading.html#L5) that way we can use it as a loading component?

**Comment by johnthepink** [comment]
say i won't

**Comment by jbaxleyiii** [comment]
@johnthepink I won't

**Comment by johnthepink** [comment]
@jbaxleyiii see what you think of that. should this be moved to core then so we can use it across the board?

**Comment by jbaxleyiii** [comment]
@johnthepink I like! Lets move it to core and add it to the controls component group. `Apollos.Controls.Loading`

I'm going to go ahead and merge this though! #progress

**Pull request merged**
